import asyncio
from typing import Any
from uuid import uuid4

import patch
from github import Github

from app.core.config import get_required_env
from app.core.repo_utils import parse_github_repo_name
from app.db.supabase_client import insert_deployment


class DeployAgent:
    def __init__(self) -> None:
        self.github_client = Github(get_required_env("GITHUB_TOKEN"))

    async def run(self, payload: dict[str, Any]) -> dict[str, Any]:
        try:
            project_id = payload["project_id"]
            repo_url = payload.get("repo_url")
            if not repo_url:
                raise ValueError("repo_url is required for deployment.")
            repo = await asyncio.to_thread(self.github_client.get_repo, parse_github_repo_name(repo_url))
            branch_name = f"ai-fde/{project_id[:8]}"
            base_branch = await asyncio.to_thread(repo.get_branch, "main")
            await self._ensure_branch(repo, branch_name, base_branch.commit.sha)
            commit_sha = base_branch.commit.sha

            for diff_obj in payload["approved_diffs"]:
                commit_sha = await self._apply_diff(
                    repo=repo,
                    branch_name=branch_name,
                    diff_obj=diff_obj,
                    task_title=payload.get("task_title", "Automated update"),
                )

            pr = await asyncio.to_thread(
                repo.create_pull,
                title=payload.get("task_title", "AI-FDE generated update"),
                body=self._build_pr_body(payload),
                base="main",
                head=branch_name,
            )

            result = {
                "pr_url": pr.html_url,
                "branch": branch_name,
                "commit_sha": commit_sha,
            }
            await insert_deployment(
                {
                    "id": str(uuid4()),
                    "project_id": project_id,
                    "task_id": payload.get("task_id"),
                    "pr_link": pr.html_url,
                    "branch_name": branch_name,
                    "commit_sha": commit_sha,
                    "status": "deployed",
                }
            )
            return result
        except Exception as exc:
            return {"status": "error", "message": str(exc)}

    async def _ensure_branch(self, repo: Any, branch_name: str, sha: str) -> None:
        def _create_branch() -> None:
            try:
                repo.get_branch(branch_name)
            except Exception:
                repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=sha)

        await asyncio.to_thread(_create_branch)

    async def _apply_diff(
        self,
        repo: Any,
        branch_name: str,
        diff_obj: dict[str, Any],
        task_title: str,
    ) -> str:
        file_path = diff_obj["file_path"]
        diff_text = diff_obj["diff"]
        content_file, original_content = await self._get_file(repo, file_path, branch_name)
        updated_content = self._materialize_content(diff_text, original_content)

        commit_message = f"feat(ai-fde): {task_title} - auto-generated by AI-FDE"
        if content_file is None:
            created = await asyncio.to_thread(
                repo.create_file,
                path=file_path,
                message=commit_message,
                content=updated_content,
                branch=branch_name,
            )
            return created["commit"].sha

        updated = await asyncio.to_thread(
            repo.update_file,
            path=file_path,
            message=commit_message,
            content=updated_content,
            sha=content_file.sha,
            branch=branch_name,
        )
        return updated["commit"].sha

    async def _get_file(self, repo: Any, file_path: str, branch_name: str) -> tuple[Any | None, str]:
        def _load() -> tuple[Any | None, str]:
            try:
                file_ref = repo.get_contents(file_path, ref=branch_name)
                return file_ref, file_ref.decoded_content.decode("utf-8", errors="ignore")
            except Exception:
                return None, ""

        return await asyncio.to_thread(_load)

    def _materialize_content(self, diff_text: str, original_content: str) -> str:
        if not diff_text.strip():
            return original_content

        if diff_text.startswith("FULL_CONTENT:\n"):
            return diff_text.removeprefix("FULL_CONTENT:\n")

        if not original_content:
            parsed_new_file = self._extract_new_file_content(diff_text)
            if parsed_new_file is not None:
                return parsed_new_file

        patch_set = patch.fromstring(diff_text.encode("utf-8"))
        if not patch_set:
            raise ValueError("Unable to parse unified diff with patch library.")

        original_lines = original_content.splitlines(keepends=True)
        updated_lines = original_lines[:]

        for patched_file in patch_set.items:
            for hunk in patched_file.hunks:
                start = max(hunk.startsrc - 1, 0)
                end = start + max(hunk.linessrc, 0)
                replacement: list[str] = []
                for line in hunk.text:
                    if line.startswith((" ", "+", "\\")):
                        if line.startswith("+") or line.startswith(" "):
                            replacement.append(line[1:])
                updated_lines[start:end] = replacement

        return "".join(updated_lines)

    def _extract_new_file_content(self, diff_text: str) -> str | None:
        lines = diff_text.splitlines()
        plus_lines = [line[1:] for line in lines if line.startswith("+") and not line.startswith("+++")]
        if plus_lines:
            return "\n".join(plus_lines) + ("\n" if diff_text.endswith("\n") else "")
        return None

    def _build_pr_body(self, payload: dict[str, Any]) -> str:
        pain_points = payload.get("pain_points") or []
        proposed_solution = payload.get("proposed_solution") or "Not provided."
        test_summary = payload.get("test_results_summary") or "No automated test summary available."
        pain_points_text = "\n".join(f"- {item}" for item in pain_points) or "- None provided"
        return (
            "## Pain Points\n"
            f"{pain_points_text}\n\n"
            "## Proposed Solution\n"
            f"{proposed_solution}\n\n"
            "## Test Results Summary\n"
            f"{test_summary}\n"
        )
